# Generated by Django 3.0.5 on 2020-09-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100)),
                ('institute_name', models.CharField(max_length=100)),
                ('course_desc', models.CharField(max_length=300)),
            ],
        ),
    ]
