# Generated by Django 3.0.5 on 2020-10-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=100)),
                ('institute_name', models.CharField(max_length=100)),
                ('course_desc', models.CharField(max_length=300)),
                ('course_image', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
